---
- name: Check date on hosts in the "poc" group
  hosts: all
  gather_facts: no
  tasks:
    - name: Get the current date and time
      command: date
      register: current_date

    - name: Display the current date and time
      debug:
        msg: "The current date and time is: {{ current_date.stdout }}"
